baseURL = "http://example.org/"
languageCode = "en-us"
title = "Eslam Mostafa"
theme = "hucore"

[params]
description = "Passionate Software Engineer"
keywords = ["Go", "Python", "Docker", "Bash", "DevOps", "Kubernetes", "CI/CD", "programming", "code", "git"]
author = "Eslam Mostafa"
sharingicons = true
copyright = "&copy; 2017 | Follow on <a href=\"https://twitter.com/emostafa_\" target=\"_blank\">Twitter</a> | <a href=\"https://github.com/mgjohansen/hucore.git\" target=\"_blank\">Hucore theme</a> & <a href=\"http://gohugo.io\" target=\"_blank\">Hugo</a> ♥"

[taxonomies]
tag = "tags"
category = "categories"

[params.highlight]
style = "github"
languages = ["go", "python", "dockerfile", "bash", "javascript"]


[[params.social]]
url = "https://github.com/emostafa"
fa_icon = "fa-github"

[[params.social]]
url = "https://linkedin.com/in/eslammostfa"
fa_icon = "fa-linkedin-square"

[[params.social]]
url = "https://reddit.com/user/emostafa"
fa_icon = "fa-reddit"

[[params.social]]
url = "https://gitlab.com/emostafa"
fa_icon = "fa-gitlab"

[[params.social]]
url = "https://twitter.com/emostafa_"
fa_icon = "fa-twitter"
